### ISSUE TITLE
You have 2 hours to create the best todo app in history. What tech do you use?

### ISSUE THREAD

**Issue by jhendley25** [passy/ama#12]

**Comment by passy** [comment]
Intriguing question.

The 2 hours constraint is pretty tough if it has to be the best app ever! I think the most reasonable choice would be Elm, because I wouldn't have to compromise on writing good code just to make the deadline. The development experience is fantastic and I wouldn't spend half of the time setting up grunt or gulp, find the right Sass compiler and fight with npm.

Also, you get persistent data structures and time travelling in Elm for free. If it's supposed to be the best Todo App ever, it has to have proper undo/redo mechanisms and that is just near-impossible to realize without the right data structures.

**Comment by jhendley25** [comment]
Awesome, thanks for the response. Looks like I'll be checking out Elm!

**Comment by romseguy** [comment]
@passy a todo app without server side rendering?
