### ISSUE TITLE
Where would you live if you could live anywhere?

### ISSUE THREAD

**Issue by sindresorhus** [passy/ama#16]
...on Earth. Sorry.

**Comment by passy** [comment]
Massive let down in the description, but still a good question despite being really hard.

I always thought it would be some sort of tropical, sunny island (that would still never have more than 25°C at any point). But London has won my heart since then. The country it's in is a mess and it has its nasty corners, but having access to so many great people and events is amazing. I'd like to have a better comparison though, so I'd like to live for a while in some other big cities like London with a thriving tech scene. New York, Seattle, Austin. Unfortunately these three are all in the USA which I could never(*) live in. I don't know much about cities in Asia that are in a similar position. May have to pick your brain about this at some point. :)

(*) Never say never, but definitely not given the current political system.
