### ISSUE TITLE
Why do you work on Open Source?

### ISSUE THREAD

**Issue by sindresorhus** [passy/ama#17]

**Comment by passy** [comment]
Good question.

Because I'm a selfish prick. Because it's the best way to learn from brilliant people like @addyosmani, @stephenplusplus and you. Yes, there's also the part about giving back and making the world better, yada, yada, yada. I do actually care about the latter and I feel that as someone who has the ability to give  back it's only fair to do so. I use so much Open Source every day. When I send packages over the internet or post something to Twitter. Billions of people benefit from the work others have done for free. I'm one of the few that actually can contribute something back. Maybe not to those critical pieces that make sure that we can all enjoy the web on our mobile phones, but even in the small you can have an impact.

**Comment by stephenplusplus** [comment]
:)

I thought I'd take this opportunity to describe us with art.

![img_5380](https://cloud.githubusercontent.com/assets/723048/9858111/ca5c61ee-5aec-11e5-88d6-66b8a2f6a9d6.jpg)

**Comment by passy** [comment]
That was absolutely beautiful.

**Comment by addyosmani** [comment]
That was truly a work of :art:

**Comment by passy** [comment]
Even coming back after a week, I'm still in awe.
