### ISSUE TITLE
How did you get into programming?

### ISSUE THREAD

**Issue by sindresorhus** [passy/ama#18]

**Comment by passy** [comment]
Great question.

It's probably the same story you've heard thousands of times before. I liked playing with my Dad's computer and in my case it was actually not so much about the games there but the entire thing. The idea of telling the computer what to do through my own programs was super intriguing. So I got some books about C++ because I heard that this is what you'd use to build graphical applications and played around with it. I still remember how incredibly excited I was when I got that very first "Hello World!" on the terminal.

After I had seen the web, however, all I wanted to do was building web sites. I started modifying exciting ones with the Netscape Composer, but found myself more and more in the source panel where you could directly change the HTML. I bought myself another book about Dynamic HTML and JavaScript and built lots of stupid little web sites I could send to my friends. Animated GIF backgrounds, framesets, hidden `ondblclick="location.href=…"`, you name it.

Well, and I've never really stopped since then. Not particularly exciting I guess, but looking back I'm really grateful of how privileged I was having all the resource available to me to learn and experiment with that stuff.
