### ISSUE TITLE
What's your all-time favorite movie?

### ISSUE THREAD

**Issue by sindresorhus** [passy/ama#20]

**Comment by passy** [comment]
I don't like favorites. I change my mind often and I think that's a healthy thing to do. I don't a favorite meal, a favorite place or a favorite MVC framework. The world is changing at such an incredible speed, I don't want to lock myself into a specific mindset or hold everything new up to what I consider to be the best of all time. Obviously, no one is immune to this and I fall into the familiarity trap as many times as everyone else when something new seems "bad" just because it's trying someone new.

All that said, there are a few recent movies I've really enjoyed. Among them Ex Machina, Nightcrawler, Birdman, Snowpiercer and Gone Girl. But sincerely hope that those weren't the best movies ever made.
