### ISSUE TITLE
What do you think comes after JS?

### ISSUE THREAD

**Issue by maxhoffmann** [passy/ama#21]
With WebAssembly, JS becoming a compiled language (ESN to ESN-1) and the increasing amount of compile-to-JS languages what do you think might be the first language to become a mainstream web programming language that compiles to JS or WebAssembly? I’m also interested in why you think it will succeed and which one you’d personally like to become mainstream.

**Comment by passy** [comment]
Wonderful question!

I personally think the fact that browser vendors acknowledge the desire to use JS as a compile-to target is more interesting than WebAssembly itself, because it is generally a change in the mindset of those people working on the JavaScript VMs. Optimizing particular ES 201X structures is going to become less relevant than the overall performance of the VM, startup time, memory footprint, etc.

This is great news for all languages running in the browser, whether they compile to "normal" JavaScript or WebAssembly. I think the future for other languages than JavaScript in the browser is bright. Google has been using Java through GWT for many, many years and even though I had a cynical look at that project, it's still going strong and powers Inbox as well as (I might be wrong here) the new super responsive Google Photos app.

I'm personally a big fan of [PureScript](http://www.purescript.org/) and [Elm](http://elm-lang.org/) because they bring the things I miss most from JavaScript (purety, immutability and equational reasoning) to the web.

I don't know if any of those languages will ever reach mainstream, but personally I don't really care. Haskell had the unofficial slogan "avoid success at all cost" for a long time and it worked really well for them. They wanted it to be a testbed for testing PL features and the result is something really impressive. Sure, a thriving ecosystem like the one Node.js makes it way easier for individual developers to find resources and building blocks, but I stopped running after the latest trend. I feel qualified enough at this point to make my own decisions about what technology solves the problem at hand best.

Back to the original question, I'm really excited about the future of the browser as a platform and having a bytecode(-ish) format for it is something I was hoping to get for a long time. I hope it's not too late with mobile platforms eating all the cake, but I'm sure we'll see a lot more work in this area.
