### ISSUE TITLE
How would you explain monads to a cat?

### ISSUE THREAD

**Issue by sindresorhus** [passy/ama#23]
The cat is brown with stripes, kinda fat, loves shrimps and cheese doodles.

**Comment by passy** [comment]
Sorry, need some clarification here. How's the cat's stance on immigration?

**Comment by sindresorhus** [comment]
No dogs allowed.

**Comment by passy** [comment]
Since I'm not a cat-ist, I'm not artificially dumbing this down for cats.

I'd just say within a Monad within a Category - aptly named - `Cat` consists of a functor `T: Cat -> Cat` with two natural transformations, `η: 1_{Cat} -> T` and `μ: T^2 -> T` where `T^2` is the functor `T . T` from `Cat` to `Cat`.

**Comment by sindresorhus** [comment]
![10607915_273427569527101_1304478306_n](https://cloud.githubusercontent.com/assets/170270/8536308/941e1268-244f-11e5-80a0-cf0c01f5bc61.jpg)
