### ISSUE TITLE
What's your favorite coffee shop in London and why?

### ISSUE THREAD

**Issue by sindresorhus** [passy/ama#27]

**Comment by passy** [comment]
Fabulous question.

![img_20150704_110504](https://cloud.githubusercontent.com/assets/9906/8507476/d6d7107e-223c-11e5-9d5b-8462f76d557c.jpg)

My number one is Trade Coffee which is also the appointed number one for the area that I live in on the [London Coffee Stops Tube Map 2015](http://workwhereyoulike.com/post/63689687510/2015-coffee-stops-tube-map).

The coffee here is excellent, staff is really nice and you can sit in their not-so-secret garden. Outside seating in E1 is rather rare otherwise.

There is, however, a very strong contender (also found on the above map) near the wonderful St. Katherine Docks: White Mulberries. It would be my overall number one if it wasn't so difficult to get a seat there. 

![img_20150301_155021-mix](https://cloud.githubusercontent.com/assets/9906/8507492/5bc43bae-223d-11e5-9165-4ce262ab28be.jpg)

If anyone reading this finds themselves looking for a coffee in the London East, give me a ping and I'll show you around.
