### ISSUE TITLE
What does the perfect programming language look like for you?

### ISSUE THREAD

**Issue by sindresorhus** [passy/ama#36]
I would assume something that takes the best parts from Haskell, Rust, Elm and PureScript?

**Comment by passy** [comment]
It's an interesting question and one I don't have a good answer for. Before I came to Haskell I always wanted to build my own language and had a lot of ideas. Now all of those no longer apply. I honestly don't know what I'd improve at Haskell except for an easier way for dependent types and type-level programming in general. In that regard Scala seems a bit more "accessible". This is all super hand-wavy, but I've read that same story a couple of times. A lot of people turn to Haskell because it provides fantastic libraries for writing parsers and compilers to build their own languages but end up liking the language so much that they stick with it. The exceptions to prove the rule are Elm and PureScript, whose compilers are both written in Haskell, but since they target different platforms that seems pretty reasonable.

I'm going to elaborate in the Rust question, but for my perfect programming language I wouldn't take much from Rust. Perfect PL implies for me that it might be impossible to achieve, but I'd much rather not having to worry about lifetimes of objects and space leaks and have some super-smart runtime that allows me to be as expressive as I can in Haskell without the shackles Rust forces onto you.
