### ISSUE TITLE
what programming language would you suggest?

### ISSUE THREAD

**Issue by robbbz** [passy/ama#37]
I am a javascript developer programming node and browser-side. Except PHP I don't know any other back-end languages. I want to learn something that I can use for web applications, but also just for other kind of programming. What language would you suggest me to use?

**Comment by passy** [comment]
Node can get you a long way. It depends whether you want to build more
things or learn more things. At the moment I don't really care too much
about building new products and shipping stuff, but want to learn more
which is why I spend most of my free time with Elm, PureScript and Haskell
which are arguably not the best choices if you just want to Get Shit Done
(even though there are huge benefits to using them once you are proficient).

Especially if you still consider yourself a starter, it might be good to
stick with JS. The community is massive, there are tons of accessible
resources for everything you can think of and the ecosystem is incredibly
vibrant. It also won't go away anytime soon.
