### ISSUE TITLE
How would you explain monads to a five year old?

### ISSUE THREAD

**Issue by hemanth** [passy/ama#41]
![image](https://cloud.githubusercontent.com/assets/18315/8759868/f8543830-2d1d-11e5-86f3-b6e7a7ce07fb.png)

**Comment by stephenplusplus** [comment]
Or, just, a "stephenplusplus"

**Comment by passy** [comment]
This is an "Ask Me Anything", but not an "Answer Anything". I won't fall into the [Monad Tutorial Trap](https://byorgey.wordpress.com/2009/01/12/abstraction-intuition-and-the-monad-tutorial-fallacy/). ;)

That said, since you've posted the picture there. When I understood what that actually means, that was one of the most rewarding moments I had with category theory. So I'll post this just as a reminder for myself:

A monoid is just a triple (M, ⊗, e) with an operation ⊗ : M × M → M and an element e ∈ M such that
this is true for all a, b, and c ∈ M:
1. a ⊗ e = a
2. e ⊗ a = a
3. a ⊗ (b ⊗ c) = (a ⊗ b) ⊗ c

A monad on the other hand is an endofunctor T : X → X with two natural transformation:
- μ : T × T → T
- η : I → T

satisfying these laws:
- μ(μ(T × T) × T)) = μ(T × μ(T × T))
- μ(η(T)) = T = μ(T(η))

Endofunctors are functors from a category to itself (which are virtually all the functors we're concerned with in FP). And in this category of endofunctors, some of the objects are monads. Which ones? Exactly those that are monoidal in a way. And without going into proofs here, just by squinting a bit at the above axioms above, you can see that there are some striking similarities.

**Comment by hemanth** [comment]
🙇
