### ISSUE TITLE
What do you think about Elixir and Phoenix?

### ISSUE THREAD

**Issue by LarsJK** [passy/ama#42]
Especially compared to Haskell and yesod (or any other web framework for Haskell..)

**Comment by passy** [comment]
Great question.

I don't have any experience with Erlang, Elixir or Phoenix, but I'm quite interesting in its development. Everything we can do to give Erlang the exposure it deserves, we should do! It's pretty crazy how much development time has gone (and continues to go) into reinventing things that the Erlang VM has mastered some 20-odd years ago.

Erlang itself always had a problem with its arcane syntax to attract users. Elixir seems to have lowered the barrier to entry remarkably. Since I've fallen in love with types, Elixir hasn't won my heart. Especially given how it kind of tries to hide the concept of immutability.

I hope that more languages like Elixir will pop up in the future, or backends of existing languages to work on top of the Erlang VM and I hope to find some time in the future to write a medium-sized toy app with Phoenix.

**Comment by stephenplusplus** [comment]
+1 to Phoenix.
