### ISSUE TITLE
What have you built with Haskell?

### ISSUE THREAD

**Issue by LarsJK** [passy/ama#43]
Do you think Haskell is a good general purpose programming language or is it better for specific use cases?

**Comment by passy** [comment]
> Do you think Haskell is a good general purpose programming language or is it better for specific use cases?

Good question. I think it is very well suited for general purpose programming. It definitely excels in certain areas like parsers and has less of a well-rounded development story like game programming, but I've tried to do most of my personal/recreational programming and automation tasks in Haskell and haven't found an area that it's unsuitable for.

Based on GitHub Stars, my [android-lint-summary](https://github.com/passy/android-lint-summary) tool is definitely the most "popular", but I've also built a Twitter bot that renders LaTeX to PNGs for you ([@ltxbot](https://twitter.com/ltxbot)) in docker containers. Apart from that, I have a lot of small scripts, algorithm and data structure katas in Haskell. The latter is always good fun because you can start implementing stuff in the familiar, imperative way first (Haskell is actually an excellent imperative language) and then try to convert it to a purely functional algorithm. This here was great because I was thinking how to do a BFS on a binary tree in a functional way and in the shower I had the epiphany that I could just treat the tree as a functor and it turned out to be completely trivial: https://github.com/passy/playground/commit/13a03b31303a3125dab2a58a53e5fdf489b7f0cf

**Comment by LarsJK** [comment]
Thanks!! 👍

Sendt fra min iPhone
