### ISSUE TITLE
What do you think about the movie Avatar?

### ISSUE THREAD

**Issue by silvenon** [passy/ama#45]
And oldie, but still.

**Comment by passy** [comment]
Good question.

Man, I know that there are some very controversial opinions on that movie, but I absolutely loved it. It was the first "real" 3D movie I've ever seen. I went to the cinema with some friends and we all enjoyed the shit out of it. Not really because of the story, but mostly because of the incredible immersion we all felt. In hindsight, it's probably not that great of a movie. Avatar is essentially Pocahontas++, but it worked for me. Today, I'm no longer a fan of 3D in movies and I'm unsure if I'd still enjoy it as much. So I'll probably not going to rewatch it to maintain that wonderful memory I have of it.

**Comment by silvenon** [comment]
Yeah, I had a similar experience. It was fun to watch indeed :grin:
