### ISSUE TITLE
Why people stress to use Immutable structures in javascript ?

### ISSUE THREAD

**Issue by asvny** [passy/ama#46]

**Comment by passy** [comment]
Great question, but I won't be able to give a good answer compared to what's already out there.

In a nutshell, it's about containing complexity. You don't really need to worry about this if you build a one-off demo on Codepen or develop a throw-away prototype in one or two days. But as soon as you start thinking about maintainability of a project or getting other people to work at it, managing complexity is one of the most important things to concern yourself with.

Computers are inherently mutable. In the end, you'll be writing to the same bits of memory. But by the same logic, we'd have to keep writing our web apps in assembler. Luckily, there are powerful abstractions that make our lives easier. Think of functions instead of gotos and direct jumps. Another one of those is immutable data structures. Immutable data structures are not about avoiding change, but about managing change and making programs easier to reason about. Mutability makes things hard. If you've ever made a defensive deep-copy of an object before passing it to a function, you've hit a case where immutability would have helped you - and would have even been faster. Another place where they are faster is for comparison and this is precisely why people keep stressing to use them in JavaScript. If keep your state that is used to render a UI in one nested mutable data structure, it's expensive to verify whether it has changed since the last frame, because you have to walk down the tree and compare each individual leaf node (or at least up to the first change). With immutable data structures this is a simple referential comparison. If the top-level variable points to the same location in memory, you know that it is in fact _the same_ object.

But I won't do this topic justice in this answer. Luckily people way smarter than me have already talked about this - a lot.

This one here is a great introduction:
[![screenshot 2015-07-22 12 53 34](https://cloud.githubusercontent.com/assets/9906/8824776/d658c25e-3070-11e5-9e2d-5f97b035d25d.png)
](https://twitter.com/passy/status/562968091575853056)

And I would be remiss not to point you to one of the many amazing talks @swanodette has given on this topic. Just pick any one:
- https://www.youtube.com/watch?v=U0xpKsKb2Bk
- https://www.youtube.com/watch?v=mS264h8KGwk
- https://www.youtube.com/watch?v=SiFwRtCnxv4
- https://www.youtube.com/watch?v=7AAXzVbfe3c
- https://www.youtube.com/watch?v=J-bC20aAat8
- https://www.youtube.com/watch?v=nDNU2pmuJA8

**Comment by asvny** [comment]
Thanks !
