### ISSUE TITLE
Color of your underwear and phone number?

### ISSUE THREAD

**Issue by robbbz** [passy/ama#51]
Sindre answered both too.

**Comment by passy** [comment]
Today's underwear is from a pack like this but with a pink writing at the top:
![](http://image1.superdry.com/static/images/products/upload7559670918789784503.jpg)

My wardrobe keeps filling up with these because I change in the morning at the gym and sometimes I forget to bring new underwear, so I have to make a trip to the Superdry store on my way to work. They're super comfy though.

With regards to the telephone number, I'm not going to answer that one. You'll probably find it if you spend 20 minutes or so on Google, but I'd rather not put it _that_ publicly out here. I really hate phone calls and I've just recently reactivated an old phone with a new SIM card just for letting agents because I don't want them to ring my main number. I'd like to have the certainty that if it rings, there's a high certainty of it being important.

With an old number I got tons of calls from people with questions about one of my apps and shit like that, so I've been burned enough to be at least a bit more careful about it now.
