### ISSUE TITLE
Do you like ES2015?

### ISSUE THREAD

**Issue by robbbz** [passy/ama#54]

**Comment by passy** [comment]
Cool question.

I think the short answer would be "no" while the long answer is a "yes, but".

I don't "like" JavaScript as a language. It's an incredible achievement for the circumstances under which it was invented and holds up fairly well against other popular languages today but on its own it's not very good. I don't think this has changed with ES2015, but it has certainly improved. So if the question is if I like ES2015 more than ES3, then the answer is a clear yes. 

Lambda functions are something we badly needed and so is the block scope. Destructuring is a great addition. When it comes to generators my initial excitement is already gone, because they add so much complexity for the language and are in the end less poweful than I would like them to be. Classes unnecessary grammar bloat that encourage users to shoot themselves in the foot. 

I don't think that ES2015 has turned JavaScript into a good language, but it probably has made it at least a slightly better one.
