### ISSUE TITLE
What does your mac dock look like?

### ISSUE THREAD

**Issue by robbbz** [passy/ama#57]

**Comment by passy** [comment]
I hide it by default and rarely use it, but that's what it looks like:

<img width="569" alt="screenshot 2015-08-27 17 48 24" src="https://cloud.githubusercontent.com/assets/9906/9526911/dd835bae-4ce3-11e5-9c45-652c075cfa92.png">

I don't like relying on OS-specific features too much, because I switch between Linux and OS X a lot.
