### ISSUE TITLE
What is your favorite fake passy twitter account?

### ISSUE THREAD

**Issue by andresdominguez** [passy/ama#6]

**Comment by passy** [comment]
That's a tough one.

I have a love-hate relationship with [@crossfitpassy](https://twitter.com/crossfitpassy). I obviously despise CrossFit, but I have to appreciate the effort the owner put into it. [@__passy](https://twitter.com/__passy) has some real gems every now and then, but is overall pretty dull. The manually curated [@passy_ebooks](https://twitter.com/passy_ebooks) has been very quiet recently, but it probably made me laugh the hardest because a lot of those quotes are wonderfully chosen out-of-context things I've said. /cc @phuu

It's like choosing your favorite child, but not for children but for clones of yourself from an experiment gone horribly wrong.
