### ISSUE TITLE
Bloodborne or MGSV?

### ISSUE THREAD

**Issue by monchote** [passy/ama#60]

**Comment by passy** [comment]
Intriguing question.

I'm not a massive fan of the horror genre (anymore). But since I'm a big fan of story-driven open world games, both are definitely interesting to me. To make a long story short, I'd go with MGSV, but given my limited time I'd probably rather wait for Fallout 4 and the Witcher 3 expansion. That said, if FO4 would turn out to be rubbish, I might pick up MGSV in a sale at some point.
