### ISSUE TITLE
How do you avoid burnout? 

### ISSUE THREAD

**Issue by RichardLitt** [passy/ama#67]
That streak is insane. How do you keep the discipline going if you're emotionally not doing well?

**Comment by passy** [comment]
I've thought a lot about this question, @RichardLitt, but I haven't found a good answer. The Wikipedia article on [Occupational Burnout](https://en.wikipedia.org/wiki/Occupational_burnout#Phases) is surprisingly good. I ended up on it after watching Jacob Kablan-Moss's stellar talk at [Open Source and Feelings](https://www.youtube.com/watch?v=EqcuzSwySR4). I see a lot of myself in this, so I'm not sure if I'm qualified to give a good answer on this.

I work a lot. There's the time I spend at my actual paid-for job and then there's this entire Open Source thing occupying a large chunk of my time in the evenings and the weekends. This can be pretty stressful at times, but there are two ingredients I've found to make it (mostly) work for me:
- _Exercise._ I work out a lot. For the past year or so I've actually spent more time at the gym than working on Open Source. It's good way to vent if you had a bad day and clear your mind. Sometimes I use it for the exact opposite and think about a hard problem from work, but I try to avoid as it's kinda crossing the streams.
- _Fun._ Find something you enjoy that isn't work-related. Sometimes work is fun, sometimes it isn't. This may sound stupid, but I know some people for whom work is all they have. And if it turns into something they no longer enjoy, they're in big trouble. I enjoy good tv shows and bought myself a PS4 earlier this year to have something that I can do in the evening if I don't feel like going through my GitHub inbox or work on a personal project. That recreational aspect can be super important when the rest of your day turns into a grind, which is sometimes hard to avoid.

I don't want to put friends on this list, because it seems too obvious and will be the first thing you hear anyway. Oh, and watch Jacob's talk. It's a bit of a downer, but it's super important.

Be really careful about burnout. There is more to it than just "Burnout Syndrome", but a long and slippery road towards it and there are certainly ways out of it if you realize soon enough that you're on it.

**Comment by RichardLitt** [comment]
Thanks!

**Comment by RichardLitt** [comment]
I do the same things, but it's hard for me to keep a streak like that going without viewing it as work. I'm still working on finding good solutions to this. I really appreciated the long answer. :)

**Comment by RichardLitt** [comment]
Hey passy; just watched that video. Thank you so much! It was great. 

I check the Wiki on Occupational Burnout fairly often, probably once a month. Of the 12 issues, I have around 10 of them present in my life at varying levels. It's not good. (Hence why I asked). Working and out and fun sure help me though, too. :)

**Comment by passy** [comment]
@RichardLitt Good luck with it, I'll turn checking that article into a habit, too. :)
