### ISSUE TITLE
Have you ever tried Polymer?

### ISSUE THREAD

**Issue by tenhobi** [passy/ama#69]

**Comment by passy** [comment]
I have! I think I have a Polymer component somewhere among my GitHub repos and the tabs on todomvc.com are currently implemented using a Polymer component. 

While I like Paper elements a lot and how easy you can prototype something with it, I would never want to build a larger applications with it. That's not Polymer's fault, but my dissatisfaction with Web Components as a whole. Too mutable, too heavy, complicated API. I can't help but feel that they grew out of curiosity rather than a need to solve an actual problem.

**Comment by tenhobi** [comment]
:+1: 

I like and use Polymer, but not their paper (or others) elements.

I think Polymer can make the development more easy and better, because it removes redundant code from the HTML. You just call/use a element you want and a lot of things may be rendered.
