### ISSUE TITLE
how does your development env look like?

### ISSUE THREAD

**Issue by ghost** [passy/ama#7]
editor/font/terminal/...

**Comment by passy** [comment]
Great question.

It depends on what I'm working on. I'm not religious when it comes to IDEs vs text editors and use whatever allows me to get stuff done more quickly. What I do need in whatever thing takes my text input is a decent vim plugin.

During my day job I work mostly on Scala or Android stuff in really big code bases and I use IntelliJ/Android Studio. I use it almost with the out-of-the-box settings, apart from the IntelliVim plugin.

For everything that isn't Scala or Java, I use neovim inside launched via [fish](http://fishshell.com/) inside a tmux inside either `gnome-terminal` or `iTerm2` depending on the OS I'm on with a Ubuntu Mono font in a [Powerline derivate](https://github.com/powerline/fonts) with either a [Solarized Dark or Light](http://ethanschoonover.com/solarized) theme depending on how bright it is where I work. I have my [dotvim](https://github.com/passy/dotvim) files on GitHub.

![screenshot 2015-07-03 10 49 38](https://cloud.githubusercontent.com/assets/9906/8497055/fad3dab4-2171-11e5-8f82-155f617072bd.png)

I still want to give [spacemacs](https://github.com/syl20bnr/spacemacs) a serious try, though, because it looks absolutely phenomenal.

I much prefer my Arch Linux environment for development which I used on my desktop PC at home, but still haven't switched for my work laptop because it seems like a pretty big pain to get everything to run smoothly on a MacBook.
