### ISSUE TITLE
What are some must-haves for a new Android user?

### ISSUE THREAD

**Issue by stephenplusplus** [passy/ama#74]
With your veteran status as an app maker on the platform, I assume you've come across some gems in your day. I recon that would help a new user of an Android phone, such as myself, and maybe others. Thanks!

**Comment by passy** [comment]
Veteran seems quite accurate indeed. Here's a non-complete list of apps that are even unique to Android or special in some other regard compared to other platforms. That means, the obvious ones like WhatsApp, Twitter aren't included as well as [all the Google apps](https://play.google.com/store/apps/dev?id=5700313618786177705&hl=en_GB) which are usually the best you can find for anything on the platform (especially [Google Photos](https://play.google.com/store/apps/details?id=com.google.android.apps.photos) which is outstanding, but I know from your tweets that you're already using it).

<img src="https://lh5.ggpht.com/jKZCC5NR0uU01scYefDjUICueE59pEpamDz3J3LDAg3X-6DupmpsDysbFUc8WUFDgfk=w300" width=75 align=left>
[Signal (formerly TextSecure)](https://play.google.com/store/apps/details?id=org.thoughtcrime.securesms&hl=en_GB) is the best messenger if you care about privacy and secrecy. Period. It's available on iOS and Android and I'm trying to convert more friends and family to use it. If you need a bigger endorsement:

![screenshot from 2015-11-29 20-27-00](https://cloud.githubusercontent.com/assets/9906/11459813/595654c4-96d7-11e5-9d2f-57f3230fcf60.png)

<img src="https://lh6.ggpht.com/KItvb_F5fVTvQg3hWNc4idE_QBDjWgu5yDseSbb9fguTbGJGRvMbLEHqAZp-eKCSDA=w300" width=75 align=left>
[Pocket Casts](https://play.google.com/store/apps/details?id=au.com.shiftyjelly.pocketcasts&hl=en_GB) is, unsurprisingly, a podcast player. I've tried a whole lot of them and this is by far my favorite. One of the few on Android with filters that remove silence from the audio. It's only a month or two since I've wiped my phone for the last time and since then it has saved me 25 hours and 45.1 minutes of silence.

<img src="https://lh3.ggpht.com/6dbDUfjcsEqWaUxfjkNMY5Obo_1xS6LcxTt3DBetr9MfkkYd6swzdsDmWmo41PTkU54O=w300" width=75 align=left>
I've only installed [IRCCloud](https://play.google.com/store/apps/details?id=com.irccloud.android&hl=en_GB) again today but it looks pretty solid. A lot has been written about [Slack and OSS](https://drewdevault.com/2015/11/01/Please-stop-using-slack.html) so I'm trying to get back into IRC.

<img src="https://lh6.ggpht.com/OYW0tpQjwUKQVFa7jDiXzYyVpZnNEoclxTAz9LTseK1gSQFPBLVpEGb3UiQP1Ec24dU=w300" width=75 align=left>
[SeriesGuide](https://play.google.com/store/apps/details?id=com.battlelancer.seriesguide&hl=en_GB) is one of those unique Android gems. If you're at all into TV Shows, this one's absolutely fantastic to keep track of upcoming episodes, new releases and collect embarrassing stats about the time you've spent in from of a TV screen.

<img src="https://lh5.ggpht.com/vbsQjG-FutTgKjw1Mb_7k04WI47DIRckM1pgk9-kJgKhS5bvAvTj8npYJQ8xO2JZZ-E=w300" width=75 align=left>
[Sleep as Android](https://play.google.com/store/apps/details?id=com.urbandroid.sleep&hl=en_GB) is an amazing sleep tracker. Crazy detailed stats and if you have a spare Android Wear Watch (yup, that's actually true for me) you can use that one to get even more accurate stats. The feature that I'm absolutely useless without is the sleep phase alarm clock that tries to wake you up when you're in light sleep.

<img src="https://lh3.googleusercontent.com/WcL0Crw46EJubniXfwCZbVgO7JF9ToVjVjPwlqCqZOhLWtrp8mGjaoh865ZXdhiG1A=w300" width=75 align=left>
Everyone loves weather apps, right? [Weather Timeline - Forecast](https://play.google.com/store/apps/details?id=com.samruston.weather&hl=en_GB) is special, though. Not super special in terms of features, but it's definitely one of the most polished apps out there. If you ever come to London, make sure to enable the rain alert. It also comes with some nice precipitation graphs letting you know when it's (probably) safe to leave the house.

<img src="https://lh4.ggpht.com/FmtkVY1R6oJ3MtbggSzUaZiteJqDmuHeA3m5ycrFM2tDtHk6Hk3pyCPrpfYyIQUwtgXA=w300" width=75 align=left>
[Pushbullet](https://play.google.com/store/apps/details?id=com.pushbullet.android&hl=en_GB) makes me hate using iOS devices. Even though they have an iOS app nowadays, the integration with Android is just so much better. Send links, photos, files directly from your desktop to your phone and vice versa. I use it multiple times a day.

<img src="https://lh3.googleusercontent.com/kzXefiHaPrMGL8EzhTOBRuPakW-guTr5Tbb_MVD9zpkFX3OLkWcOIYkT6GDfo9uw0DV4kLGwzQ=s50-h50-e365" width=75 align=left>

This one's a bit odd, because the link for [Vysor](https://chrome.google.com/webstore/detail/vysor-beta/gidgenkbbabolejbgbpnhbimgjbffefm) goes to the Chrome and not the Play Store. It's an incredible piece of software that mirrors your device screen on your desktop. The most astounding thing is that it requires absolutely zero setup, apart from you having to enable the developer mode - which I suspect you have already done. There were so many people who tried to make this work before but this is arguably the first time someone actually did.

I think that covers the Android-specific, non-Google apps that I'd recommend to everyone. There are some more specific ones like [Yatse](https://play.google.com/store/apps/details?id=org.leetzone.android.yatsewidgetfree&hl=en_GB) which is a must-have if you have a Kodi player in your house or [Telecine](https://play.google.com/store/apps/details?id=com.jakewharton.telecine&hl=en_GB) if you want to record your screen - but that seems a bit more niche.

**Comment by getsetbro** [comment]
Recommendations on Android Wear Watches?
