### ISSUE TITLE
how did you learn haskell?

### ISSUE THREAD

**Issue by ghost** [passy/ama#8]
I always fail after a minute or 20. What resources did you use? What books did you read? Thanks.

**Comment by passy** [comment]
I started by reading [Learn You a Haskell for Great Good!](http://learnyouahaskell.com/). There are varying opinions about, but I still love it and highly recommend it to everyone. I mean, look at how happy I am in this picture!

![img_20150702_204715](https://cloud.githubusercontent.com/assets/9906/8486404/3cd5f8fa-20fc-11e5-81e3-787e009dd39d.jpg)

It is, however, very easy to get discouraged. After I read the book I wanted to write some stuff and I have a depth-first attitude when it comes to programming languages. This simply doesn't work for Haskell. I pulled in a library that seemed helpful and instead of just using it, I wanted to understand how all the constructions worked and ended up somewhere [deep down in nlab](http://ncatlab.org/nlab/show/Courant+algebroid) and didn't know whether I should laugh or cry. (I chose the latter.)

There are [awesome resources](https://github.com/krispo/awesome-haskell) out there and the community is unbelievably helpful and welcoming, especially if you come from a community similiar to the one JavaScript represents. If you have a question, ask it in IRC in `#haskell-beginners` or post it on StackOverflow and you'll have your answer in a couple of minutes.

Make the right trade-offs between diving deep into a topic and practicing the new stuff you learned. The type safety is what attracted me, but category theory is what kept me there. But make sure to pick one topic at a time and don't go all the way from Functor to Applicative to Bind to Monad to Arrow in one go. But if you want to go down the category theory rabbit hole, I can recommend [Categories and computer science by Richard F. Walters](https://www.google.co.uk/search?q=Categories+and+computer+science+Book+by+Richard+F.+Walters) as a rather approachable lecture.

But most importantly, write and read some code along the way. @Gabriel439 (second time I mention him in one of my answers) writes superb code that is always brilliantly documented, oftentimes accompanied by a `.Tutorial` module that not only gives you code examples but explains how it all works together.

So, I still have a long way to go, but it's definitely worth it. It has changed the way I write code in every language substantially and gives me new ways to reason about code and structure my APIs. It's an investment that pays off.

**Comment by arthurvr** [comment]
Neat answer @passy. I read a copy of that exact same book but never dug deeper into Haskell. Thanks for the reminder that I have to do that, one day :tada:
