### ISSUE TITLE
Curious what keyboard and mouse you use

### ISSUE THREAD

**Issue by lonelydatum** [passy/ama#80]

**Comment by passy** [comment]
Excellent question, but one without a simple answer because I tend to type on a lot of different things throughout the day.

I won't talk about the one in my MacBook Pro because it's a disaster and I try to minimise the time I type on it as much as possible.

Let's start with my work setup.

![mvimg_20180315_130732](https://user-images.githubusercontent.com/9906/37554608-38345c6e-29d3-11e8-9de6-bfb983d2e57e.jpg)

I have a beefy Lenovo ThinkStation under my desk and a MacBook Pro running Synergy to connect the two. The ThinkStation comes with a keyboard, which is the one at the top, which is surprisingly good for a throw-in accessory. It's not great, but I'd choose it over any Apple keyboard. I use it for one purpose only: entering my dmcrypt passphrase on boot.

The bottom keyboard is my main input device and is a [DasKeyboard 4 Professional](https://www.daskeyboard.com/daskeyboard-4-professional/) in the silent edition. I mean, I'm not that much of an asshole to go with Cherry MX Blue switches in an office setting.

My work mouse is a [Logitech MX Master AMZ](https://www.amazon.co.uk/gp/product/B0761YL588/). It's wireless but comes with an micro USB-B port for charging *that you plug into while using your mouse*. The battery life is way over a week, though, so I rarely use it tethered. One silly reason why I like this one a lot for work is that it has an automatic unlock for flinging the scroll wheel. Super handy when scrolling through long diffs.

Remember what I said about not being a dick using noisy keyboards? That doesn't apply at home!

![videoplayback](https://user-images.githubusercontent.com/9906/37554701-6d7813a6-29d4-11e8-85dd-e8797b982887.gif)

Here I went with an utterly ridiculous [Razer Chroma X](https://www.amazon.co.uk/Razer-BlackWidow-Mechanical-Keyboard-Construction/dp/B01DCMNQSU/r) which I absolutely adore. The switches are very close to Cherry MX Brown in tactility and ... well, noisiness. 

My actual configuration is a bit more muted and only highlights the recently used keys in pink. Because why not.

[![mvimg_20180317_112017](https://user-images.githubusercontent.com/9906/37554781-63617cee-29d5-11e8-92cf-95ac969747a1.jpg)](https://www.dropbox.com/s/hc9xqxbiv7stcur/VID_20180317_110253.mp4?dl=0)
(Click for video)

And my mouse is a rather boring but reliable [Logitech G700S](http://support.logitech.com/en_gb/product/g700s-rechargable-wireless-gaming-mouse).

Thanks for asking!
