### ISSUE TITLE
Why do you hate shell scripts?

### ISSUE THREAD

**Issue by hemanth** [passy/ama#9]
I heard you hate them, but why?!

**Comment by passy** [comment]
Love that question!

I think that shell scripts are great for exactly one purpose: save one-liners you otherwise manually type into your terminal. You may think that this is something you could use `alias` or simple function definitions in your `~/.profile` for and you're totally right about that. The nice thing about saving them as a file is that you can easily share them. But that's it. Don't add that second line. Please. I beg you.

So what's so bad about them? The worst thing is that the above scenario is exactly how 99% of all 500+ line scripts starts. It's a couple of lines, maybe a for loop over some files, then you add something else because you forgot to handle a small edge case and then you end up with this unwielding mess of string concatenation and trap functions. Consistency? Nope.

I see many, many shell scripts every day and all of them are their own unique snowflake. No consistency whatsoever, no clear entry points. If you're really lucky, you'll find some functions in them. But those aren't real functions, of course. If you run any of those through [shellcheck](https://github.com/koalaman/shellcheck) you'll get roughty one error every other line. Ever tried to run one of those scripts with an argument (like a directory) that contained a space? Just be sure to hover your fingers over Ctrl+C, because chances are good you're about to delete your hard drive.

But the difference between `$arg` and `"$arg"` is just one of many issues that drive me nuts about the actual "language". The insane defaults for error handling are way worse. Sure, for an interactive REPL it's probably not desirable to end the whole session as soon as we try to `cd` into a directory that doesn't exist, but for a program we sure as hell want it to terminate our assumptions about the current working directory are untrue. And how many times do you actually see that `set -e` at the top of shell scripts you execute?

Then there's portability. Yes, those people from Cupertino really, really don't like the GPL, but those BSD tools are still freaking awful. And it doesn't help that I can `brew install` some stuff that adds a proper `gdf` to my path if that now means I have to check for both `gdf` and `df`. And I'm not even talking about this other OS that with its backslashes.

Can we do better? Of course we can, and most of us do every day. There are _real_ programming languages out there. There are brilliant alternatives out there that try to give you all the comfort of easy accessible commands while giving you strong compile-time guarantees like @Gabriel439's [turtle](http://www.haskellforall.com/2015/01/use-haskell-for-shell-scripting.html) and every modern operating system comes with at least Python these days.

We can do so much better. Shell scripts make me sad.

**Comment by hemanth** [comment]
> But that's it. Don't add that second line. Please. I beg you.

I understand your pain :+1: 

`turtle` looks like fun (:

Thanks for such a detailed reply!
